config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'events#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  class << self
    def build(params, current_user)
      event = Event.new(params)
      event.user = current_user
      event
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  class << self
    def find_or_create_from_auth_hash(auth)
      find_by(provider: auth['provider'], uid: auth['uid']) || create_with_omniauth!(auth)
    end

    def create_with_omniauth!(auth)
      create! do |u|
        u.provider = auth['provider']
        u.email = auth['info']['email'].presence || ''
        u.uid = auth['uid']
      end
    end
  end

  def update_if_needed!(auth)
    new_email = auth['info']['email']
    if new_email.present? && email != new_email
      self.email = new_email
    end
    save! if changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :check_logged_in

  helper_method :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def check_logged_in
    redirect_to login_path unless logged_in?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.build(event_params, current_user)

    if @event.save
      redirect_to events_url, notice: t('messages.created', model: Event.model_name.human)
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to events_url, notice: t('messages.updated', model: Event.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: t('messages.destroyed', model: Event.model_name.human)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :start_at, :end_at, :url, :place_name, :memo)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_logged_in
  protect_from_forgery except: [:create]

  def new
  end

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    @user.update_if_needed!(auth_hash)
    session[:user_id] = @user.id
    redirect_to events_url
  end

  def destroy
    session.destroy
    redirect_to root_url
  end

  protected
    def auth_hash
      request.env['omniauth.auth']
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def attributes_t(label)
    I18n.t("activerecord.attributes.#{label}")
  end
end

app/views/application/_login.html.slim
a.google[href="/auth/google_oauth2", class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent"]
  | Login with Google Account
- if Rails.env.development?
  hr
  a.google[href="/auth/developer", class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent"]
    | Log in with develop

app/views/events/_form.html.slim
= form_with(model: @event) do |f|
  - if @event.errors.any?
    ul
      - @event.errors.full_messages.each do |message|
        li = message

  .mdl-textfield.mdl-js-textfield
    = f.label :name, class: 'mdl-textfield__label'
    = f.text_field :name, class: 'mdl-textfield__input', id: :event_name
  br
  .mdl-textfield.mdl-js-textfield
    = f.label :start_at, class: 'mdl-textfield__label'
    = f.date_field :start_at, class: 'mdl-textfield__input', id: :event_start_at
  br
  .mdl-textfield.mdl-js-textfield
    = f.label :end_at, class: 'mdl-textfield__label'
    = f.date_field :end_at, class: 'mdl-textfield__input', id: :event_end_at
  br
  .mdl-textfield.mdl-js-textfield
    = f.label :url, class: 'mdl-textfield__label'
    = f.text_field :url, class: 'mdl-textfield__input', id: :event_url
  br
  .mdl-textfield.mdl-js-textfield
    = f.label :place_name, class: 'mdl-textfield__label'
    = f.text_field :place_name, class: 'mdl-textfield__input', id: :event_place_name
  br
  .mdl-textfield.mdl-js-textfield
    = f.label :memo, class: 'mdl-textfield__label'
    = f.text_field :memo, class: 'mdl-textfield__input', id: :event_memo
  br
  .actions = f.submit class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent'

app/views/events/edit.html.slim
h3
  = t('messages.edit', model: Event.model_name.human)

== render 'form'

app/views/events/index.html.slim
= javascript_pack_tag 'MyCalendar'

h3.logo-font イベントリスト

= link_to '登録', new_event_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent'

- if @events.present?
  hr

  .scroll-box
    table.mdl-data-table.mdl-js-data-table.mdl-shadow--2dp
      thead
        tr
          th.mdl-data-table__cell--non-numeric = attributes_t('event.name')
          th.mdl-data-table__cell--non-numeric = attributes_t('event.start_at')
          th.mdl-data-table__cell--non-numeric = attributes_t('event.end_at')
          th.mdl-data-table__cell--non-numeric = attributes_t('event.place_name')
          th.mdl-data-table__cell--non-numeric = attributes_t('event.memo')
          th
          th
          th

      tbody
        - @events.each do |event|
          tr
            td = event.name
            td = event.start_at
            td = event.end_at
            td = event.place_name
            td = event.memo
            td = link_to event.url, event.url, target: '_blank'
            td = link_to '編集', edit_event_path(event)
            td = link_to '削除', event, data: { confirm: '本当によろしいですか?' }, method: :delete

  hr
  div#calendar

app/views/events/new.html.slim
h3
  = t('messages.new', model: Event.model_name.human)

== render 'form'

app/views/index/index.html.slim
h1 Index#index
p Find me in app/views/index/index.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title
      | Myvent
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    link[rel="manifest" href="/manifest.json"]
    link[rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons"]
    link[rel="stylesheet" href="//code.getmdl.io/1.3.0/material.light_green-red.min.css"]
    script[defer src="//code.getmdl.io/1.3.0/material.min.js"]
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

  body
    .mdl-layout.mdl-js-layout.mdl-layout--fixed-header
      header.mdl-layout__header
        .mdl-layout__header-row
          span.mdl-layout-title
            | Myvent
          .mdl-layout-spacer
      - if logged_in?
        .mdl-layout__drawer
          span.mdl-layout-title
            | menu
          nav.mdl-navigation
            = link_to 'Logout', logout_url, class: 'mdl-navigation__link'
      main.mdl-layout__content
        .mdl-grid
          .mdl-layout-spacer
          .mdl-cell--8-col
            = yield
          .mdl-layout-spacer
      div[aria-live="assertive" aria-atomic="true" aria-relevant="text" class="mdl-snackbar mdl-js-snackbar"]
        .mdl-snackbar__text
        button[type="button" class="mdl-snackbar__action"]

      - if notice
        javascript:
          window.addEventListener("DOMContentLoaded",function(eve){
            var notification = document.querySelector('.mdl-js-snackbar');
            if(notification.MaterialSnackbar) {
              notification.MaterialSnackbar.showSnackbar({message: '#{notice}'});
            }
          },false);